site_name: Project6 MicroCRM
site_url: https://github.com/olivierPflieger/Project6/
theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
nav:
  - Accueil: index.md
  - Pipeline: pipeline.md
  - Pipeline infra: pipeline-infra.md
  - Pipeline Rollback: pipeline-rollback.md
  - Commandes Monitoring: monitoring.md
  - Commandes Back-End : backend.md
  - Tests Back-End : testing-backend.md
  - Commandes Front-End : frontend.md
  - Tests Front-End : testing-frontend.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format