{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}

metadata:
  name: microcrm-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: microcrm-frontend

  {{- if .Values.rollout.enabled }}
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 60m
        - setWeight: 100
  {{- end }}

  template:
    metadata:
      labels:
        app: microcrm-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}