# SonarCloud

sonar.projectKey=Project6-Organisation_Project6-Application
sonar.projectName=Project6-Application
sonar.organization=project6-organisation
sonar.host.url=https://sonarcloud.io

# Source code

sonar.sources=src
sonar.tests=src

# Coverage (Karma)

sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info

# Inclusions and Exclusions

sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts

# Encoding

sonar.sourceEncoding=UTF-8

# Quality Gate

sonar.qualitygate.wait=true