# SonarCloud

sonar.projectKey=Project6-Organisation_Project6-Application
sonar.projectName=Project6-Application
sonar.organization=project6-organisation
sonar.host.url=https://sonarcloud.io

# Source code

sonar.sources=src/main/java
sonar.tests=src/test/java

# Java

sonar.java.source=17
sonar.java.binaries=build/classes/java/main

# Test reports

# sonar.junit.reportPaths=build/test-results/test

# Coverage (JaCoCo)

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Exclusions

sonar.exclusions=**/build/**

# Encoding

sonar.sourceEncoding=UTF-8

# Quality Gate

sonar.qualitygate.wait=true