{
 "title": "Show microCRM http traffic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "app",
    "label": "Aplication",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   { "name": "status", "label": "Status Code", "query": "200,201,401,404,500, " },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"}\n    != \"ELB-HealthChecker/2.0\"\n    | json\n    | logger=\"http.log.access.log0\"\n    [${__range}]\n  )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Success Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"}\n    != \"ELB-HealthChecker/2.0\"\n    | json\n    | logger=\"http.log.access.log0\"\n    | status < 400\n    [${__range}]\n  )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Bad Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"}\n    != \"ELB-HealthChecker/2.0\"\n    | json\n    | logger=\"http.log.access.log0\"\n    | status >= 400 and status < 500\n    [${__range}]\n  )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Errored Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"}\n    != \"ELB-HealthChecker/2.0\"\n    | json\n    | logger=\"http.log.access.log0\"\n    | status >= 500\n    [${__range}]\n  )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=~\"$app\", namespace=~\"$namespace\"}\n  != \"ELB-HealthChecker/2.0\"\n  | json\n  | logger=\"http.log.access.log0\"\n  | keep status\n  [1m]\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app=~\"$app\", namespace=~\"$namespace\", level=~\"$level\"}\n!= \"ELB-HealthChecker/2.0\"\n| json\n| status=~\"$status\"\n| line_format \"{{.request_method}} {{.request_uri}} -> {{.status}} ({{.duration}} s)\""
    }
   ]
  }
 ]
}