grafana:
  enabled: true
  
  ingress:
    enabled: true

    ingressClassName: alb

    hosts:
      - microcrm-grafana.prod.olivierpflieger.fr

    path: /

    pathType: Prefix

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:161438779240:certificate/af9ef7c4-5e92-4323-a81d-b19f549d7e4b

  dashboards:
    default:
      kubernetes-global:
        file: dashboards/k8s-global-views.json
      kubernetes-namespaces:
        file: dashboards/k8s-view-namespaces.json
      kubernetes-nodes:
        file: dashboards/k8s-view-nodes.json
      kubernetes-pods:
        file: dashboards/k8s-view-pods.json
      dashboard-oc:
        file: dashboards/dashboard-oc.json
      dashboard-dora:
        file: dashboards/dashboard-dora.json

  grafana.ini:
    smtp:
      enabled: true
      host: live.smtp.mailtrap.io:587
      user: $__env{SMTP_USER}
      password: $__env{SMTP_PASSWORD}
      from_address: hello@demomailtrap.co
      from_name: Grafana Alerts
      startTLS_policy: MandatoryStartTLS

  envFromSecret: grafana-smtp-secret

  alerting:
    contactpoints.yaml:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: email-devops
          receivers:
            - uid: email-devops
              type: email
              settings:
                addresses: keryss@gmail.com
                singleEmail: false

    policies.yaml:
      apiVersion: 1
      policies:
        - orgId: 1
          receiver: email-devops
          group_by:
            - grafana_folder
            - alertname
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h

    rules.yaml:
      apiVersion: 1
      groups:
        - orgId: 1
          name: alertes microcrm
          folder: Kubernetes
          interval: 1m
          rules:
            - uid: afrht8s81y58ge
              title: Pod Memory Usage High
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: |
                      100 *
                      (
                        container_memory_working_set_bytes{namespace=~"microcrm-.*", container!="", image!=""}
                        /
                        on(namespace,pod,container)
                        kube_pod_container_resource_limits{namespace=~"microcrm-.*", resource="memory"}
                      )
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  queryType: expression
                  datasourceUid: __expr__
                  model:
                    conditions:
                      - evaluator:
                          params:
                            - 80
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                            - C
                        reducer:
                          params: []
                          type: last
                        type: query
                    datasource:
                      type: __expr__
                      uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 1m
              annotations:
                summary: Pod memory usage above 80%
              labels: {}
              isPaused: false
              notification_settings:
                receiver: email-devops

            - uid: cpuusagehigh
              title: Pod CPU Usage High
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: |
                      100 *
                      (
                        rate(container_cpu_usage_seconds_total{namespace=~"microcrm-.*", container!="", image!=""}[5m])
                        /
                        on(namespace,pod,container)
                        kube_pod_container_resource_limits{namespace=~"microcrm-.*", resource="cpu"}
                      )
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  queryType: expression
                  datasourceUid: __expr__
                  model:
                    conditions:
                      - evaluator:
                          params:
                            - 80
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                            - C
                        reducer:
                          params: []
                          type: last
                        type: query
                    datasource:
                      type: __expr__
                      uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 1m
              annotations:
                summary: Pod CPU usage above 80%
              labels: {}
              isPaused: false
              notification_settings:
                receiver: email-devops

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 5d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi