grafana:
  enabled: true
  
  ingress:
    enabled: true

    ingressClassName: alb

    hosts:
      - microcrm-grafana.staging.olivierpflieger.fr

    path: /

    pathType: Prefix

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:161438779240:certificate/af9ef7c4-5e92-4323-a81d-b19f549d7e4b

  dashboards:
    default:
      kubernetes-global:
        file: dashboards/k8s-global-views.json
      kubernetes-namespaces:
        file: dashboards/k8s-view-namespaces.json
      kubernetes-nodes:
        file: dashboards/k8s-view-nodes.json
      kubernetes-pods:
        file: dashboards/k8s-view-pods.json
      dashboard-oc:
        file: dashboards/dashboard-oc.json
      dashboard-dora:
        file: dashboards/dashboard-dora.json

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false



# Un dernier point à vérifier

# Comme tu es sur EKS 1.33, je te conseille de lancer avant le changement :

# kubectl get storageclass

# et de me donner le résultat.

# Je vérifierai que la StorageClass par défaut de ton cluster est bien compatible avec ce storageSpec (c'est souvent gp2, gp3 ou ebs-csi sur EKS). Si elle est correcte, tu n'auras rien d'autre à configurer.

# prometheus:
#   prometheusSpec:
#     retention: 5d

#     storageSpec:
#       volumeClaimTemplate:
#         spec:
#           accessModes:
#             - ReadWriteOnce

#           resources:
#             requests:
#               storage: 1Gi