namespace: microcrm-prod

backend:
  image:
    tag: v1.6.0
  replicas: 2

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

frontend:
  image:
    tag: v1.6.0
  replicas: 2

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingress:
  enabled: true
  host: microcrm.prod
  apiHost: microcrm-api.prod
  certificateArn: arn:aws:acm:us-east-1:161438779240:certificate/af9ef7c4-5e92-4323-a81d-b19f549d7e4b

rollout:
  enabled: true
  