namespace: microcrm-staging

backend:
  image:
    tag: develop-16c2d7a
  replicas: 1

frontend:
  image:
    tag: develop-16c2d7a
  replicas: 2

ingress:
  enabled: true
  host: microcrm.staging
  apiHost: microcrm-api.staging
  certificateArn: arn:aws:acm:us-east-1:161438779240:certificate/6a892dd9-ad2b-4586-ace3-e7d386898faf