namespace: microcrm-staging

backend:
  image:
    tag:
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi

frontend:
  image:
    tag:
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingress:
  enabled: true
  host: microcrm.staging
  apiHost: microcrm-api.staging
  certificateArn: arn:aws:acm:us-east-1:161438779240:certificate/af9ef7c4-5e92-4323-a81d-b19f549d7e4b

rollout:
  enabled: false