name: Integration_BackEnd_Build

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          required: true

jobs:
  BackEnd_Build:
    
    name: Analyse BackEnd application with SonarQube
    
    runs-on: ubuntu-latest
        
    steps:

      - name: Checkout repository Application
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: application

      - name: Checkout repository Integration
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Download backend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: application/back/build
      
      - name: Fix permissions for SonarQube Quality Gate summary script
        working-directory: integration
        run: |
          chmod +x scripts/sonar-quality-gate-summary.sh

      - name: Cache SonarQube packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Copy Sonar properties
        run: |
          cp integration/sonar/sonar-backend.properties \
            application/back/sonar-project.properties

      - name: Analyze BackEnd application with SonarQube
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: application/back          

      - name: Display SonarQube Quality Gate summary
        working-directory: integration
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./scripts/sonar-quality-gate-summary.sh \
            "Project6-Organisation_Project6-Application" \
            "${GITHUB_REF_NAME}"    

# name: Integration_BackEnd_Build

# on:
#   workflow_call:
#     secrets:
#         SONAR_TOKEN:
#           required: true

# jobs:
#   BackEnd_Build:
    
#     name: Build BackEnd application and analyze with SonarQube
    
#     runs-on: ubuntu-latest
    
#     steps:

#       - name: Checkout repository Application
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#           path: application

#       - name: Checkout  repository Integration
#         uses: actions/checkout@v4
#         with:
#           repository: Project6-Organisation/Project6-Integration
#           path: integration
          
#       - name: Fix permissions for Gradle
#         working-directory: application/back
#         run: |
#           chmod +x ./gradlew

#       - name: Fix permissions for SonarQube Quality Gate summary script
#         working-directory: integration
#         run: |
#           chmod +x scripts/sonar-quality-gate-summary.sh

#       - name: Cache Gradle
#         uses: actions/cache@v4
#         if: success()
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.gradle/wrapper
#           key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         
#       - name: Cache SonarQube packages
#         uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
#         with:
#           path: ~/.sonar/cache
#           key: ${{ runner.os }}-sonar
#           restore-keys: ${{ runner.os }}-sonar
      
#       - name: Build BackEnd application and analyze
#         working-directory: application/back
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           echo "Building BackEnd application"
#           ./gradlew clean build -x test sonar --info -Dsonar.qualitygate.wait=true

#       - name: Display SonarQube Quality Gate summary
#         working-directory: integration
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           ./scripts/sonar-quality-gate-summary.sh \
#             "Project6-Organisation_Project6-Application" \
#             "${GITHUB_REF_NAME}"