name: BackEnd_SonarQube

on:
  workflow_call:
    secrets:
        SONAR_TOKEN_BACKEND:
          required: true

jobs:
  BackEnd_Build:
    
    name: Analyse BackEnd application with SonarQube
    
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest
        
    steps:

      - name: Checkout repository Application
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: application

      - name: Checkout repository Integration
        uses: actions/checkout@v6
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Download backend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: application/back/build

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-report
          path: application/back/build/reports/jacoco/test
      
      - name: Fix permissions for SonarQube Quality Gate summary script
        working-directory: integration
        run: |
          chmod +x scripts/sonar-quality-gate-summary.sh

      - name: Cache SonarQube packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Copy Sonar properties
        run: |
          cp integration/sonar/sonar-backend.properties \
            application/back/sonar-project.properties

      - name: Analyze BackEnd application with SonarQube
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
          
        with:
          projectBaseDir: application/back

      - name: Display SonarQube Quality Gate summary
        working-directory: integration
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        run: |
          ./scripts/sonar-quality-gate-summary.sh \
            "Project6-Organisation_Project6-Application-Backend" \
            "${GITHUB_REF_NAME}" \
            "BackEnd"