name: FrontEnd_Build

on:
  workflow_call:

jobs:
  FrontEnd_Build:
    
    name: Build FrontEnd application
    
    runs-on: [self-hosted, project6]

    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v6

      - name: Debug Node
        run: |
          echo "PATH=$PATH"
          which node
          which npm
          node -v
          npm -v
      
      - name: Cache npm
        uses: actions/cache@v5
        if: success()
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build FrontEnd application
        if: success()
        run: |
          echo "Building FrontEnd application"
          npm ci
          npm run build
      
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: front/dist