name: FrontEnd_SonarQube

on:
  workflow_call:
    secrets:
        SONAR_TOKEN_FRONTEND:
          required: true

jobs:
  FrontEnd_SonarQube:
    
    name: Analyse FrontEnd application with SonarQube
    
    runs-on: ubuntu-latest
        
    steps:

      - name: Checkout repository Application
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: application

      - name: Checkout repository Integration
        uses: actions/checkout@v6
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: application/front/dist

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: front-coverage-report
          path: application/front/coverage
      
      - name: Fix permissions for SonarQube Quality Gate summary script
        working-directory: integration
        run: |
          chmod +x scripts/sonar-quality-gate-summary.sh

      - name: Cache SonarQube packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Copy Sonar properties
        run: |
          cp integration/sonar/sonar-frontend.properties \
            application/front/sonar-project.properties

      - name: Analyze FrontEnd application with SonarQube
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          
        with:
          projectBaseDir: application/front

      - name: Display SonarQube Quality Gate summary
        working-directory: integration
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        run: |
          ./scripts/sonar-quality-gate-summary.sh \
            "Project6-Organisation_Project6-Application" \
            "${GITHUB_REF_NAME}" \
            "FrontEnd"