name: FrontEnd_docker_Build

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string   
      is_release:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read

jobs:
  FrontEnd_Build:
    
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, project6]

    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4
      
      - name: Compute image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --target front \
            -t "$IMAGE_NAME:$IMAGE_TAG" \
            -t "$IMAGE_NAME:latest" \
            .

      - name: Push Docker image
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
          docker push "$IMAGE_NAME:latest"

      - name: Show pushed image
        run: |
          echo "Pushed image: $IMAGE_NAME:$IMAGE_TAG"
          echo "Pushed image: $IMAGE_NAME:latest"