name: FrontEnd_docker_Build

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string   
      is_release:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read

jobs:
  FrontEnd_Docker_Build:
    
    runs-on: [self-hosted, project6]
    #runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Assign and display image name
        run: |
          echo "inputs.image_tag: ${{ inputs.image_tag }}"
          echo "inputs.is_release: ${{ inputs.is_release }}"
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/frontend" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t "$IMAGE_NAME:$IMAGE_TAG" \
            -t "$IMAGE_NAME:latest" \
            .

      - name: Scan Frontend image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: table
          exit-code: '1'
          output: 'back-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: back-trivy-results
          path: back-trivy-results.txt
          retention-days: 1

      - name: Push Docker image
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
          docker push "$IMAGE_NAME:latest"

      - name: Show pushed image
        run: |
          echo "Pushed image: $IMAGE_NAME:$IMAGE_TAG"
          echo "Pushed image: $IMAGE_NAME:latest"