name: Integration

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          required: false

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
  
jobs:
  Check-variables:
    runs-on: ubuntu-latest
    steps:      
            
      - name: Show trigger type
        run: |
          echo "Triggered by: ${{ github.event_name }}"
      
      - name: Show caller & called workflow branch
        run: |
          echo "Caller branch: ${{ github.ref_name }}"
          echo "Called pipeline branch: main"

      - name: Check SonarQube token
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          [ -n "$SONAR_TOKEN" ] && echo "SONAR_TOKEN OK" || echo "SONAR_TOKEN IS MISSING"
    
  BackEnd_Build:
    uses: ./.github/workflows/01_1_BackEnd_Build.yml
    secrets: inherit
    
  BackEnd_Test:
    needs:
      - BackEnd_Build
    uses: ./.github/workflows/01_2_BackEnd_Test.yml
    secrets: inherit

  BackEnd_SonarQube:
    if: |
      github.ref_name == 'develop'
    needs:
      - BackEnd_Test
    uses: ./.github/workflows/01_3_BackEnd_SonarQube.yml
    secrets: inherit
    
  FrontEnd_Build:
    uses: ./.github/workflows/01_4_FrontEnd_Build.yml
    secrets: inherit

  FrontEnd_Test:
    needs:
      - FrontEnd_Build
    uses: ./.github/workflows/01_5_FrontEnd_Test.yml
    secrets: inherit