name: Integration

on:
  workflow_call:
    secrets:
        SONAR_TOKEN_BACKEND:
          required: false
        SONAR_TOKEN_FRONTEND:
          required: false
        SNYK_TOKEN:
          required: false
        SNYK_ORG_ID:
          required: false
    inputs:
      origin:
        required: false
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
  
jobs:
  Check-variables:
    
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest
    
    steps:      
      
      - name: Show caller & called workflow branch
        run: |
          echo "Triggered by : ${{ github.event_name }}"
          echo "Action       : ${{ github.event.action }}"

          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"

          if [ "${{ inputs.origin }}" == "manual-trigger" ]; then
            echo "Caller branch: ${{ github.ref_name }}"
            echo "Called pipeline branch: develop"
          else
            echo "Caller branch: ${{ github.ref_name }}"
            echo "Called pipeline branch: main"
          fi

      - name: Check SonarQube token
        env:
          SONAR_TOKEN_BACKEND: ${{ secrets.SONAR_TOKEN_BACKEND }}
          SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        run: |
          [ -n "$SONAR_TOKEN_BACKEND" ] && echo "SONAR_TOKEN_BACKEND OK" || echo "SONAR_TOKEN_BACKEND IS MISSING"
          [ -n "$SONAR_TOKEN_FRONTEND" ] && echo "SONAR_TOKEN_FRONTEND OK" || echo "SONAR_TOKEN_FRONTEND IS MISSING"

      - name: Check Snyk token
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        run: |
          [ -n "$SNYK_TOKEN" ] && echo "SNYK_TOKEN OK" || echo "SNYK_TOKEN IS MISSING"
          [ -n "$SNYK_ORG_ID" ] && echo "SNYK_ORG_ID OK" || echo "SNYK_ORG_ID IS MISSING"

  BackEnd_Build:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - Check-variables
    uses: ./.github/workflows/01_1_BackEnd_Build.yml
    secrets: inherit
    
  BackEnd_Test:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - BackEnd_Build
    uses: ./.github/workflows/01_2_BackEnd_Test.yml
    secrets: inherit

  BackEnd_SonarQube:
    #if: |
    #  github.ref_name == 'develop'
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - BackEnd_Test
    uses: ./.github/workflows/01_3_BackEnd_SonarQube.yml
    secrets: inherit
    
  FrontEnd_Build:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - Check-variables
    uses: ./.github/workflows/01_4_FrontEnd_Build.yml
    secrets: inherit

  FrontEnd_Test:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - FrontEnd_Build
    uses: ./.github/workflows/01_5_FrontEnd_Test.yml
    secrets: inherit

  FrontEnd_SonarQube:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    if: |
      github.ref_name == 'develop'
    needs:
      - FrontEnd_Test
    uses: ./.github/workflows/01_6_FrontEnd_SonarQube.yml
    secrets: inherit

  Snyk_Scan:
    # Desactivation temporaire du build
    if: false
    # End desactivation temporaire du build
    needs:
      - BackEnd_Build
      - FrontEnd_Build
    uses: ./.github/workflows/01_7_Snyk.yml
    secrets: inherit

  CI_Status:
    name: CI Status
    
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest

    needs:
      - BackEnd_Build
      - BackEnd_Test
      - FrontEnd_Build
      - FrontEnd_Test
      - BackEnd_SonarQube
      - FrontEnd_SonarQube
      - Snyk_Scan

    if: always()

    steps:
      - run: echo "All checks passed"