name: Docker build and push artifacts on Github package registry

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      image_tag:
        value: ${{ jobs.Semantic_Release.outputs.image_tag }}      
    
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  
jobs:
  
  Check-variables:
    
    runs-on: ubuntu-latest
        
    steps:      
            
      - name: Show caller & called workflow branch
        run: |
          echo "Triggered by : ${{ github.event_name }}"
          echo "Action       : ${{ github.event.action }}"

          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"

      - name: Check environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          if [ "${{ inputs.environment }}" != "staging" ] && [ "${{ inputs.environment }}" != "prod" ]; then
            echo "Invalid environment: ${{ inputs.environment }}"
            echo "Allowed values: staging, prod"
            exit 1
          fi
  
  Semantic_Release:

    needs:
      - Check-variables

    runs-on: ubuntu-latest
    
    outputs:
      is_release: ${{ steps.compute-image-tag.outputs.is_release }}
      release_version: ${{ steps.semantic-release.outputs.new_release_version }}
      image_tag: ${{ steps.compute-image-tag.outputs.image_tag }}
    
    steps:

      - name: Checkout repository Application
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: application

      - name: Checkout repository Integration
        uses: actions/checkout@v6
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Copy semantic-release config
        run: |
          cp integration/release.config.cjs \
            application/front/release.config.cjs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: application/front/package-lock.json

      - name: Install Semantic Release
        working-directory: application/front
        run: |
          npm ci
          npm install --save-dev \
            semantic-release \
            @semantic-release/github
            # @semantic-release/changelog \
            # @semantic-release/git \

      - name: Semantic Release
        id: semantic-release
        working-directory: application/front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BEFORE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          npx semantic-release

          AFTER_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ "$BEFORE_TAG" != "$AFTER_TAG" ]; then
            echo "New release published"
            echo "new_release_published=true" >> "$GITHUB_OUTPUT"
            echo "new_release_version=${AFTER_TAG#v}" >> "$GITHUB_OUTPUT"
          else
            echo "No new release published"
            echo "new_release_published=false" >> "$GITHUB_OUTPUT"
            echo "new_release_version=" >> "$GITHUB_OUTPUT"
          fi
           
      - name: Compute image tag
        id: compute-image-tag
        run: |
          if [ "${{ steps.semantic-release.outputs.new_release_published }}" = "true" ]; then
            image_tag="v${{ steps.semantic-release.outputs.new_release_version }}"
            is_release="true"
          else
            image_tag="${GITHUB_REF_NAME}-${GITHUB_SHA::7}"
            is_release="false"
          fi

          echo "Computed image tag: $image_tag"
          echo "Is release: $is_release"
          
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "is_release=$is_release" >> "$GITHUB_OUTPUT"
              
  Docker_Build_BackEnd:

    needs:
      - Semantic_Release

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./back
        
    steps:
      - uses: actions/checkout@v4

      - name: Assign and display image name
        run: |
          echo "inputs.image_tag: ${{ needs.Semantic_Release.outputs.image_tag }}"
          echo "inputs.is_release: ${{ needs.Semantic_Release.outputs.is_release }}"
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/backend" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ needs.Semantic_Release.outputs.image_tag }}" >> $GITHUB_ENV
            
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t "$IMAGE_NAME:$IMAGE_TAG" \
            -t "$IMAGE_NAME:latest" \
            .

      - name: Scan Backend image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: table
          exit-code: '0'
          output: 'back-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: back-trivy-results
          path: back-trivy-results.txt
          retention-days: 1

      - name: Push Docker image
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
          docker push "$IMAGE_NAME:latest"

      - name: Show pushed image
        run: |
          echo "Pushed image: $IMAGE_NAME:$IMAGE_TAG"
          echo "Pushed image: $IMAGE_NAME:latest"
  
  Docker_Build_FrontEnd:

    needs:
      - Semantic_Release
    
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    defaults:
      run:
        working-directory: ./front
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Assign and display image name
        run: |
          echo "inputs.image_tag: ${{ needs.Semantic_Release.outputs.image_tag }}"
          echo "inputs.is_release: ${{ needs.Semantic_Release.outputs.is_release }}"
          
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/frontend" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ needs.Semantic_Release.outputs.image_tag }}" >> $GITHUB_ENV
          echo "API_BASE_URL=https://microcrm-api.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg API_BASE_URL="$API_BASE_URL" \
            -t "$IMAGE_NAME:$IMAGE_TAG" \
            -t "$IMAGE_NAME:latest" \
            .

      - name: Scan Frontend image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: table
          exit-code: '0'
          output: 'front-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: front-trivy-results
          path: front-trivy-results.txt
          retention-days: 1

      - name: Push Docker image
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
          docker push "$IMAGE_NAME:latest"

      - name: Show pushed image
        run: |
          echo "Pushed image: $IMAGE_NAME:$IMAGE_TAG"
          echo "Pushed image: $IMAGE_NAME:latest"