name: Deployment application

on:
  workflow_call:
    
    secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
      
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  contents: read
  packages: read
  issues: write

jobs:
  
  deploy-monitoring:

    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest
    
    name: Deploy Monitoring Stack

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Helm repositories
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Create monitoring namespace
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Loki
        run: |
          helm upgrade --install loki grafana/loki \
            --namespace monitoring \
            --set deploymentMode=SingleBinary \
            --set loki.auth_enabled=false \
            --set loki.commonConfig.replication_factor=1 \
            --set loki.storage.type=s3 \
            --set loki.storage.bucketNames.chunks="project6-terraform-loki-${{ inputs.environment }}-230620261146" \
            --set loki.storage.bucketNames.ruler="project6-terraform-loki-${{ inputs.environment }}-230620261146" \
            --set loki.storage.bucketNames.admin="project6-terraform-loki-${{ inputs.environment }}-230620261146" \
            --set loki.storage.s3.region="${{ vars.AWS_REGION }}" \
            --set singleBinary.replicas=1 \
            --set read.replicas=0 \
            --set write.replicas=0 \
            --set backend.replicas=0

      - name: Install Prometheus and Grafana
        run: |
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --set grafana.enabled=true \
            --set grafana.adminPassword=admin

      - name: Check monitoring
        run: |
          kubectl get pods -n monitoring
          kubectl get svc -n monitoring

  deploy-helm:

    needs: deploy-monitoring
    
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    steps:

      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration
      
      - name: Check environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          if [ "${{ inputs.environment }}" != "staging" ] && [ "${{ inputs.environment }}" != "prod" ]; then
            echo "Invalid environment: ${{ inputs.environment }}"
            echo "Allowed values: staging, prod"
            exit 1
          fi

      - name: Check image tag
        run: |
          echo "Image Tag: ${{ inputs.image_tag }}"
          if [ "${{ inputs.image_tag }}" = "" ]; then
            echo "Invalid image tag: ${{ inputs.image_tag }}"
            exit 1
          fi

      - name: Display environment variables
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name project6-eks-${{ inputs.environment }}

      - name: Check cluster access
        run: |
          kubectl get nodes

      - name: Deploy application with Helm
        run: |
          helm upgrade --install microcrm integration/helm \
            -f integration/helm/values-${{ inputs.environment }}.yaml \
            --namespace microcrm-${{ inputs.environment }} \
            --create-namespace \
            --set backend.image.tag=${{ inputs.image_tag }} \
            --set frontend.image.tag=${{ inputs.image_tag }} \
            --set ingress.baseDomain=$BASE_DOMAIN \
            --atomic \
            --wait \
            --timeout 5m

      - name: Display application URL
        run: |
          echo "Waiting for Ingress ALB URL..."

          INGRESS_URL=""

          for i in {1..30}; do
            INGRESS_URL=$(kubectl get ingress microcrm-ingress \
              -n microcrm-${{ inputs.environment }} \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -n "$INGRESS_URL" ]; then
              break
            fi

            echo "Ingress ALB not ready yet... retry $i/30"
            sleep 10
          done

          if [ -z "$INGRESS_URL" ]; then
            echo "Ingress ALB URL not found"
            kubectl describe ingress microcrm-ingress -n microcrm-${{ inputs.environment }}
            exit 1
          fi

          echo "ALB URL: https://$INGRESS_URL"
          APP_URL="https://microcrm.${{ inputs.environment }}.$BASE_DOMAIN"
          echo "Application URL: $APP_URL"
          echo "### Application deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ALB URL: https://$INGRESS_URL" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Application URL: $APP_URL" >> $GITHUB_STEP_SUMMARY
          echo "API URL: $APP_URL/api" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "OVH domain configuration: edit DNS record (CNAME)" >> $GITHUB_STEP_SUMMARY
          echo "microcrm.${{ inputs.environment }} => $INGRESS_URL." >> $GITHUB_STEP_SUMMARY

      - name: Check deployment
        run: |
          kubectl get pods -n microcrm-${{ inputs.environment }}
          kubectl get svc -n microcrm-${{ inputs.environment }}

      - name: Send DORA deployment event to Loki
        if: always()
        run: |
          kubectl run dora-sender-${{ github.run_id }} \
            --rm -i --restart=Never \
            --image=curlimages/curl:latest \
            --namespace=monitoring \
            --command -- sh -c '
              curl -X POST "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push" \
                -H "Content-Type: application/json" \
                -d "{
                  \"streams\": [
                    {
                      \"stream\": {
                        \"job\": \"github-actions\",
                        \"type\": \"dora\",
                        \"environment\": \"${{ inputs.environment }}\",
                        \"repository\": \"${{ github.repository }}\"
                      },
                      \"values\": [
                        [
                          \"$(date +%s%N)\",
                          \"deployment run_id=${{ github.run_id }} status=${{ job.status }} sha=${{ github.sha }} workflow=${{ github.workflow }}\"
                        ]
                      ]
                    }
                  ]
                }"
            '

  zap_scan-BackEnd:
  
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest
    
    name: Scan the BackEnd application with OWASP ZAP

    needs: deploy-helm

    environment: ${{ inputs.environment }}

    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    # Desactivation temporaire du build
    if: false
    # if: inputs.environment == 'staging'
    # End desactivation temporaire du build
  
    steps:

      - name: Show URL to scan
        run: |
          echo "URL to scan : https://microcrm-api.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"

      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "https://microcrm-api.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"
          docker_name: zaproxy/zap-stable
          fail_action: false
          artifact_name: "zap_report_backend.html"

  zap_scan-FrontEnd:
  
    runs-on: [self-hosted, project6]
    # runs-on: ubuntu-latest
    
    name: Scan the FrontEnd application with OWASP ZAP

    needs: deploy-helm

    environment: ${{ inputs.environment }}

    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    # Desactivation temporaire du build
    if: false
    # if: inputs.environment == 'staging'
    # End desactivation temporaire du build
  
    steps:

      - name: Show URL to scan
        run: |
          echo "URL to scan : https://microcrm.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"

      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "https://microcrm.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"
          docker_name: zaproxy/zap-stable
          fail_action: false
          artifact_name: "zap_report_frontend.html"