name: Deployment application

on:
  workflow_call:
    
    secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
      
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string      

permissions:
  contents: read
  packages: read
  issues: write

jobs:
  
  deploy-helm:
        
    # runs-on: [self-hosted, project6]
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    steps:

      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration
      
      - name: Check environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          if [ "${{ inputs.environment }}" != "staging" ] && [ "${{ inputs.environment }}" != "prod" ]; then
            echo "Invalid environment: ${{ inputs.environment }}"
            echo "Allowed values: staging, prod"
            exit 1
          fi

      - name: Check parameters
        run: |
          echo "Image Tag: ${{ inputs.image_tag }}"
          if [ "${{ inputs.image_tag }}" = "" ]; then
          echo "Invalid image tag: ${{ inputs.image_tag }}"
          exit 1
          fi          

      - name: Display environment variables
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"          

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name project6-eks-${{ inputs.environment }}

      - name: Check cluster access
        run: |
          kubectl get nodes

      - name: Check Argo Rollouts
        if: inputs.environment == 'prod'
        run: |
          kubectl get pods -n argo-rollouts
          kubectl get crd rollouts.argoproj.io

      - name: Deploy application with Helm
        run: |
          if [ "${{ inputs.environment }}" = "prod" ]; then
            helm upgrade --install microcrm integration/helm \
              -f integration/helm/values-prod.yaml \
              --namespace microcrm-prod \
              --create-namespace \
              --set backend.image.tag=${{ inputs.image_tag }} \
              --set frontend.image.tag=${{ inputs.image_tag }} \
              --set ingress.baseDomain=$BASE_DOMAIN \
              --timeout 10m
          else
            helm upgrade --install microcrm integration/helm \
              -f integration/helm/values-staging.yaml \
              --namespace microcrm-staging \
              --create-namespace \
              --set backend.image.tag=${{ inputs.image_tag }} \
              --set frontend.image.tag=${{ inputs.image_tag }} \
              --set ingress.baseDomain=$BASE_DOMAIN \
              --wait \
              --atomic \
              --timeout 10m
          fi

      - name: Install Argo Rollouts CLI
        if: inputs.environment == 'prod'
        run: |
          curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
          chmod +x kubectl-argo-rollouts-linux-amd64
          sudo mv kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

      - name: Check canary rollouts
        if: inputs.environment == 'prod'
        run: |
          kubectl argo rollouts get rollout microcrm-frontend \
            -n microcrm-${{ inputs.environment }}

          kubectl argo rollouts get rollout microcrm-backend \
            -n microcrm-${{ inputs.environment }}
      
      - name: Display application URL
        run: |
          echo "Waiting for Ingress ALB URL..."

          INGRESS_URL=""

          for i in {1..30}; do
            INGRESS_URL=$(kubectl get ingress microcrm-ingress \
              -n microcrm-${{ inputs.environment }} \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -n "$INGRESS_URL" ]; then
              break
            fi

            echo "Ingress ALB not ready yet... retry $i/30"
            sleep 10
          done

          if [ -z "$INGRESS_URL" ]; then
            echo "Ingress ALB URL not found"
            kubectl describe ingress microcrm-ingress -n microcrm-${{ inputs.environment }}
            exit 1
          fi

          echo "ALB URL: https://$INGRESS_URL"
          APP_URL="https://microcrm.${{ inputs.environment }}.$BASE_DOMAIN"
          echo "Application URL: $APP_URL"
          echo "### Application deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ALB URL: https://$INGRESS_URL" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Application URL: $APP_URL" >> $GITHUB_STEP_SUMMARY
          echo "API URL: $APP_URL/api" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "OVH domain configuration: edit DNS record (CNAME)" >> $GITHUB_STEP_SUMMARY
          echo "microcrm.${{ inputs.environment }} => $INGRESS_URL." >> $GITHUB_STEP_SUMMARY

      - name: Check deployment
        run: |
          kubectl get pods -n microcrm-${{ inputs.environment }}
          kubectl get svc -n microcrm-${{ inputs.environment }}
        
      # WITH GITHUB RUNNER
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.12"

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install requests
      
      - name: push DORA metrics
        #  Switch to prod !!!!
        if: inputs.environment == 'prod'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          kubectl -n monitoring port-forward svc/pushgateway-prometheus-pushgateway 9091:9091 &
          PF_PID=$!

          sleep 5

          OUTPUT=$(python integration/scripts/dora-calculate-lead-time.py \
            "${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.repository_owner }}" \
            "${{ github.event.repository.name }}" \
            "${{ github.sha }}")

          echo "$OUTPUT"

          LEAD_TIME_SECONDS=$(echo "$OUTPUT" | tail -n1)

          cat <<EOF | curl --fail --data-binary @- "http://127.0.0.1:9091/metrics/job/dora/service/microcrm/environment/${{ inputs.environment }}/commit/${{ github.sha }}"
          dora_deployment_total 1
          dora_deployment_success_total 1
          dora_change_failure_total 0
          dora_lead_time_seconds $LEAD_TIME_SECONDS
          EOF

          kill $PF_PID
            
  zap_scan-BackEnd:
  
    # runs-on: [self-hosted, project6]
    runs-on: ubuntu-latest
    
    name: Scan the BackEnd application with OWASP ZAP

    needs: deploy-helm

    environment: ${{ inputs.environment }}

    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    # Desactivation temporaire du build
    #if: false
    # End desactivation temporaire du build
  
    steps:

      - name: Show URL to scan
        run: |
          echo "URL to scan : https://microcrm-api.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"

      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "https://microcrm-api.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"
          docker_name: zaproxy/zap-stable
          fail_action: false
          artifact_name: "zap_report_backend.html"

  zap_scan-FrontEnd:
  
    # runs-on: [self-hosted, project6]
    runs-on: ubuntu-latest
    
    name: Scan the FrontEnd application with OWASP ZAP

    needs: deploy-helm

    environment: ${{ inputs.environment }}

    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

    # Desactivation temporaire du build
    #if: false    
    # End desactivation temporaire du build
  
    steps:

      - name: Show URL to scan
        run: |
          echo "URL to scan : https://microcrm.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"

      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "https://microcrm.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"
          docker_name: zaproxy/zap-stable
          fail_action: false
          artifact_name: "zap_report_frontend.html"