name: FrontEnd_docker_Build

on:
  workflow_call:
    
    secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true        
      
    inputs:
      action:
        required: true
        type: string   
      
permissions:
  contents: read

jobs:
  eks-infra:
    runs-on: [self-hosted, project6]

    defaults:
      run:
        working-directory: integration/infra/eks

    steps:

      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Check action
        run: |
          echo "Action: ${{ inputs.action }}"
          if [ "${{ inputs.action }}" != "apply" ] && [ "${{ inputs.action }}" != "destroy" ]; then
            echo "Invalid action: ${{ inputs.action }}"
            echo "Allowed values: apply, destroy"
            exit 1
          fi  

      - name: Create bucket if not exists
        run: |
          aws s3api head-bucket \
            --bucket project6-terraform-state \
            2>/dev/null \
            || aws s3 mb s3://project6-terraform-state --region us-east-1
      
      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: inputs.action == 'plan'
        run: terraform plan -out=tfplan
      
      - name: Terraform apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve 