name: Deploy EKS infrastructure with Terraform

on:
  workflow_call:
    
    secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
      
    inputs:
      action:
        required: true
        type: string   
      environment:
        required: true
        type: string

permissions:
  contents: read

jobs:
  create-infra:
    runs-on: [self-hosted, project6]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1

    defaults:
      run:
        working-directory: integration/infra/eks

    steps:

      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Check action
        run: |
          echo "Action: ${{ inputs.action }}"
          if [ "${{ inputs.action }}" != "plan" ] && [ "${{ inputs.action }}" != "apply" ] && [ "${{ inputs.action }}" != "destroy" ]; then
            echo "Invalid action: ${{ inputs.action }}"
            echo "Allowed values: plan, apply, destroy"
            exit 1
          fi

      - name: Check environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          if [ "${{ inputs.environment }}" != "staging" ] && [ "${{ inputs.environment }}" != "prod" ]; then
            echo "Invalid environment: ${{ inputs.environment }}"
            echo "Allowed values: staging, prod"
            exit 1
          fi

      - name: Create bucket if not exists
        run: |
          aws s3api head-bucket \
            --bucket project6-terraform-state-230620261146 \
            2>/dev/null \
            || aws s3 mb s3://project6-terraform-state-230620261146 --region us-east-1
      
      - name: Terraform init
        run: |
          terraform init \
            -backend-config="key=eks/${{ inputs.environment }}/terraform.tfstate"

      - name: Terraform format
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: inputs.action == 'plan' || inputs.action == 'apply'
        run: terraform plan -var-file="envs/${{ inputs.environment }}.tfvars" -out=tfplan
      
      - name: Terraform apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -var-file="envs/${{ inputs.environment }}.tfvars" -auto-approve