name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout du code
        uses: actions/checkout@v6

      - name: Checkout Application repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Application
          path: application

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Installer MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Copy README du Project6-Application
        run: |
          cp application/README.md docs/Project6-Application.md
          cp application/front/src/favicon.png docs/front/src/favicon.png
          cp application/misc/screenshots/screenshot_2.png docs/misc/screenshots/screenshot_2.png

      - name: Déployer le site
        run: mkdocs gh-deploy --force

      