name: Integration

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          required: false

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
  
jobs:
  Check-variables:
    runs-on: ubuntu-latest
    steps:      
            
      - name: Show trigger type
        run: |
          echo "Triggered by: ${{ github.event_name }}"
      
      - name: Show caller & called workflow branch
        run: |
          echo "Caller branch: ${{ github.ref_name }}"
          echo "Called workflow branch: develop"

      - name: Check SonarQube token
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          [ -n "$SONAR_TOKEN" ] && echo "SONAR_TOKEN OK" || echo "SONAR_TOKEN IS MISSING"
  
  # Applications build
  BackEnd_Build:
    uses: ./.github/workflows/Integration_BackEnd_Build.yml
    secrets: inherit
    
  FrontEnd_Build:
    uses: ./.github/workflows/Integration_FrontEnd_Build.yml
    secrets: inherit

  # Applications tests
  BackEnd_Test:
    needs:
      - BackEnd_Build
    uses: ./.github/workflows/Integration_BackEnd_Test.yml
    secrets: inherit

  FrontEnd_Test:
    needs:
      - FrontEnd_Build
    uses: ./.github/workflows/Integration_FrontEnd_Test.yml
    secrets: inherit

  # SonarQube analysis
  # BackEnd_SonarQube:
  #   needs:
  #     - BackEnd_Build
  #     - BackEnd_Test
  #   uses: ./.github/workflows/Integration_BackEnd_SonarQube.yml
  #   secrets: inherit